version: '3.8'
services:
  backend:
    build: ./ApiBackendDia
    ports:
      - "8091:8080"
    env_file:
      - ./ApiBackendDia/my-go-project/.env
    restart: unless-stopped
    networks:
      - app-network
  frontend:
    build: ./ApiFrontendDia
    ports:
      - "8092:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

  proxy-backend:
    build: ./proxy-backend
    ports:
      - "3002:3001"
    env_file:
      - ./proxy-backend/.env
    restart: unless-stopped
    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "ho.el-jumillano.com.ar:200.80.131.34"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge      